# Use clang instead of GCC due to ICE with GCC versions 12 & 13 on ppc64le.
# For more details, see: https://github.com/libjxl/libjxl/issues/3387
c_compiler:
  - clang    # [ppc64le]
c_compiler_version:
  - 18       # [ppc64le]
cxx_compiler:
  - clangxx  # [ppc64le]
cxx_compiler_version:
  - 18       # [ppc64le]
