setlocal EnableDelayedExpansion

mkdir build
cd build

cmake %CMAKE_ARGS% ^
      -DCMAKE_FIND_ROOT_PATH="%LIBRARY_PREFIX%" ^
      -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ^
      -DBUILD_TESTING:BOOL=OFF ^
      -DBUILD_SHARED_LIBS:BOOL=ON ^
      -DJPEGXL_ENABLE_TOOLS:BOOL="%JPEGXL_ENABLE_TOOLS%" ^
      -DJPEGXL_ENABLE_DOXYGEN:BOOL=OFF ^
      -DJPEGXL_ENABLE_MANPAGES:BOOL=OFF ^
      -DJPEGXL_ENABLE_BENCHMARK:BOOL=OFF ^
      -DJPEGXL_ENABLE_EXAMPLES:BOOL=OFF ^
      -DJPEGXL_BUNDLE_LIBPNG:BOOL=OFF ^
      -DJPEGXL_ENABLE_SJPEG:BOOL=OFF ^
      -DJPEGXL_ENABLE_SKCMS:BOOL=ON ^
      -DJPEGXL_STATIC:BOOL=OFF ^
      -DJPEGXL_FORCE_SYSTEM_BROTLI:BOOL=ON ^
      -DJPEGXL_FORCE_SYSTEM_HWY:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_AVX3:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_AVX3:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_AVX3_SPR:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_AVX3_ZEN4:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_RVV:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_SSSE3:BOOL=ON ^
      -DJPEGXL_ENABLE_HWY_SVE_256:BOOL=ON ^
      ..
if errorlevel 1 exit 1

cmake --build . --config Release --target install --parallel "%CPU_COUNT%"
if errorlevel 1 exit 1
