{% set version = "0.11.1" %}
{% set skcms_version = "42030a771244ba67f86b1c1c76a6493f873c5f91" %}
{% set jpeg_turbo_version = "8ecba3647edb6dd940463fedf38ca33a8e2a73d1" %}

package:
  name: libjxl-split
  version: {{ version }}

source:
  - url: https://github.com/libjxl/libjxl/archive/v{{ version }}.tar.gz
    sha256: 1492dfef8dd6c3036446ac3b340005d92ab92f7d48ee3271b5dac1d36945d3d9
    patches:
      # Fix https://github.com/libjxl/libjxl/pull/582
      - patches/0001-CHECK_EXCLUDE_LIBS.patch
      # Remove libm dependency when building with Windows/macOS (fixed upstream in 0.12+ partially, but in our case since we use clang it needs to exclude WIN32 and not just MSVC), remove this patch when upgrading after whole fix is in upstream)
      - patches/0002-BACKPORT_FIX_LM_PKGCONFIG_LIBJXL_CMAKE.patch
      # Similar to 0002-BACKPORT_FIX_LM_PKGCONFIG_LIBJXL_CMAKE.patch but for libjxl_cms.cmake
      # This one has never been fixed upstream as of 9 january 2026.
      - patches/0003-FIX_LM_PKGCONFIG_LIBJXL_CMS_CMAKE.patch
      # Similar to 0002-BACKPORT_FIX_LM_PKGCONFIG_LIBJXL_CMAKE.patch but for libjxl_threads.cmake
      # This one has never been fixed upstream as of 11 january 2026.
      - patches/0004-FIX_LM_PKGCONFIG_LIBJXL_THREADS_CMAKE.patch
  # No tags, versions, or stable ABIs are exposed in the skcms repo
  # so I don't think it fits well in conda's versioning system.
  - git_url: https://skia.googlesource.com/skcms
    git_rev: {{ skcms_version }}
    folder: third_party/skcms
  # They pull in 3 headers from here and copy them into jpegli
  - url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ jpeg_turbo_version }}.tar.gz
    sha256: ed729127097af5000bfeddc6b3e679c4363bb1618ebfc07efb6b47f576471b4b
    folder: third_party/libjpeg-turbo

build:
  number: 6
  script:
    - mkdir build

outputs:
  - name: libjxl
    build:
      script_env:
        - JPEGXL_ENABLE_TOOLS=OFF
      run_exports:
        - {{ pin_subpackage('libjxl', min_pin='x.x', max_pin='x.x') }}
      ignore_run_exports:
        - libbrotlicommon
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - pkg-config
        - cmake >=3.16
        - make  # [not win]
      host:
        - brotli
        - libhwy
    script: install.sh  # [not win]
    script: install.bat  # [win]
    test:
      commands:
        - test -f "$PREFIX"/include/jxl/encode.h  # [not win]
        - test -f "$PREFIX"/lib/libjxl"$SHLIB_EXT"  # [not win]
        - test ! -f "$PREFIX"/bin/cjxl  # [not win]
        - if not exist %LIBRARY_INC%\\jxl\\encode.h exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\jxl.dll exit 1  # [win]
        - if exist %LIBRARY_BIN%\\cjxl.exe exit 1  # [win]

        # CFEP-18: Static libs shouldn't be part of the main package
        - test ! -f "$PREFIX"/lib/libjxl.a  # [not win]
        - if exist %LIBRARY_LIB%\\jxl-static.lib exit 1  # [win]
  - name: libjxl-tools
    build:
      script_env:
        - JPEGXL_ENABLE_TOOLS=ON
      ignore_run_exports:
        - libbrotlicommon
        - libzlib
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - pkg-config
        - cmake
        - make  # [not win]
      host:
        - brotli
        - libhwy
        - giflib
        - libjpeg-turbo
        - openexr
        - libpng
        - zlib  # by libpng
        - {{ pin_subpackage('libjxl', exact=True) }}
      run:
        - {{ pin_subpackage('libjxl', exact=True) }}
    script: install.sh  # [not win]
    script: install.bat  # [win]
    test:
      requires:
        - pkg-config
        - {{ compiler('c') }}  # [not win]
        - clang                # [win]
      files:
        - test_pkgconfig_link.sh   # [not win]
        - test_pkgconfig_link.bat  # [win]
      commands:
        - cjxl --version
        - djxl --version
        - cjpegli --help
        - djpegli --help
        - jxlinfo --help

        # Encode & decode tests
        - printf "P6 1 1 63 000" > test.ppm  # [not win]
        - echo | set /p dummy="P6 1 1 63 000" > test.ppm  # [win]
        - cjxl test.ppm test.jxl
        - djxl test.jxl test.ppm
        - jxlinfo test.jxl
        # tests libjxl correct linking via pkg-config
        - pkg-config --print-errors --exact-version "{{ version }}" libjxl
        # does a minimal compile/link/test of a program using libjxl and libjxl_threads
        - bash test_pkgconfig_link.sh  # [not win]
        - test_pkgconfig_link.bat      # [win]

about:
  home: https://jpeg.org/jpegxl/
  summary: JPEG XL image format reference implementation
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - third_party/skcms/LICENSE
  dev_url: https://github.com/libjxl/libjxl
  description: |
    This repository contains a reference implementation of JPEG XL (encoder and decoder),
    called libjxl. This software library is used by many applications that support JPEG XL.

    `libjxl` provides the core library.
    For `cjxl`, `djxl`, `libjxl_extras_codec`, and other tools, use `libjxl-tools`.

extra:
  recipe-maintainers:
    - sshockwave
  feedstock-name: libjxl
